export interface Product {
  id: number;
  slug: string;
  name: string;
  shortName: string;
  price: number;
  oldPrice: number;
  priceStr: string;
  oldPriceStr: string;
  scale: string;
  category: "1:32" | "1:24" | "1:18" | "RC" | "Frame";
  img: string;
  images: string[];
  badge: string | null;
  description: string;
  features: string[];
  inStock: boolean;
  sku: string;
}

const PRODUCTS: Product[] = [
  /* ── 1:24 ──────────────────────────────────────────────── */
  {
    id: 1,
    slug: "range-rover-pearl-white-124",
    name: "1:24 Land Rover Range Rover – Pearl White",
    shortName: "Range Rover Pearl White",
    price: 1299,
    oldPrice: 1799,
    priceStr: "₹1,299",
    oldPriceStr: "₹1,799",
    scale: "1:24",
    category: "1:24",
    img: "/images/car-suv.png",
    images: ["/images/car-suv.png", "/images/car-phantom.png"],
    badge: "Sale",
    description:
      "A stunning 1:24 scale die-cast replica of the iconic Land Rover Range Rover finished in Pearl White. Features opening doors, detailed interior, rubber tyres, and a metal body with incredible paint quality.",
    features: [
      "Die-cast metal body",
      "Opening doors & bonnet",
      "Detailed interior",
      "Rubber tyres",
      "Pull-back mechanism",
      "Display stand included",
    ],
    inStock: true,
    sku: "DXM-124-001",
  },
  {
    id: 2,
    slug: "rolls-royce-phantom-black-124",
    name: "1:24 Rolls Royce Phantom – Midnight Black",
    shortName: "Rolls Royce Phantom Black",
    price: 1499,
    oldPrice: 1999,
    priceStr: "₹1,499",
    oldPriceStr: "₹1,999",
    scale: "1:24",
    category: "1:24",
    img: "/images/car-phantom.png",
    images: ["/images/car-phantom.png", "/images/car-suv.png"],
    badge: "Hot",
    description:
      "Commanding presence in 1:24 scale — the Rolls Royce Phantom in midnight black finish. Ultra-detailed die-cast metal construction with chrome accents, functional doors, and a luxury presentation box.",
    features: [
      "Die-cast metal body",
      "Chrome trim accents",
      "Opening doors",
      "Luxury gift box",
      "Collector certificate",
      "1:24 scale accuracy",
    ],
    inStock: true,
    sku: "DXM-124-002",
  },
  {
    id: 3,
    slug: "military-jeep-green-124",
    name: "1:24 Military Off-Road Jeep – Army Green",
    shortName: "Military Jeep Army Green",
    price: 999,
    oldPrice: 1299,
    priceStr: "₹999",
    oldPriceStr: "₹1,299",
    scale: "1:24",
    category: "1:24",
    img: "/images/car-jeep.png",
    images: ["/images/car-jeep.png"],
    badge: null,
    description:
      "Rugged 1:24 scale military Jeep replica in authentic army green. Die-cast body with detailed roll bars, spare tyre, and working suspension. Perfect for military vehicle collectors.",
    features: [
      "Die-cast metal body",
      "Military green finish",
      "Roll bar detail",
      "Spare tyre on rear",
      "Detailed dashboard",
      "Heavy-duty rubber tyres",
    ],
    inStock: true,
    sku: "DXM-124-003",
  },
  {
    id: 4,
    slug: "vintage-sedan-brown-124",
    name: "1:24 Classic Vintage Sedan – Heritage Brown",
    shortName: "Classic Vintage Sedan",
    price: 1199,
    oldPrice: 1599,
    priceStr: "₹1,199",
    oldPriceStr: "₹1,599",
    scale: "1:24",
    category: "1:24",
    img: "/images/car-vintage.png",
    images: ["/images/car-vintage.png"],
    badge: "New",
    description:
      "Step back in time with this gorgeous 1:24 scale 1930s vintage sedan in heritage brown. Hand-painted details, wire-spoke wheels, and period-correct interior make this a collector's dream.",
    features: [
      "Hand-painted detailing",
      "Wire-spoke wheel replicas",
      "Period-correct interior",
      "Antique chrome trim",
      "Display plinth included",
      "Collector series",
    ],
    inStock: true,
    sku: "DXM-124-004",
  },

  /* ── 1:18 ──────────────────────────────────────────────── */
  {
    id: 5,
    slug: "ford-f150-black-118",
    name: "1:18 Ford F-150 Raptor – Matte Black",
    shortName: "Ford F-150 Raptor Black",
    price: 2499,
    oldPrice: 3199,
    priceStr: "₹2,499",
    oldPriceStr: "₹3,199",
    scale: "1:18",
    category: "1:18",
    img: "/images/car-pickup.png",
    images: ["/images/car-pickup.png"],
    badge: "Sale",
    description:
      "The ultimate 1:18 scale Ford F-150 Raptor in stealth matte black. Every inch of this model screams precision — from the functional suspension to the textured off-road tyres. A centrepiece for any collection.",
    features: [
      "1:18 scale precision",
      "Matte black finish",
      "Working suspension",
      "Heavy off-road tyres",
      "Full interior detail",
      "Opening doors + bonnet",
    ],
    inStock: true,
    sku: "DXM-118-001",
  },
  {
    id: 6,
    slug: "cullinan-white-118",
    name: "1:18 Rolls Royce Cullinan – Pearl White",
    shortName: "Rolls Royce Cullinan White",
    price: 2999,
    oldPrice: 3799,
    priceStr: "₹2,999",
    oldPriceStr: "₹3,799",
    scale: "1:18",
    category: "1:18",
    img: "/images/car-suv.png",
    images: ["/images/car-suv.png"],
    badge: "Hot",
    description:
      "The Rolls Royce Cullinan in 1:18 scale — a true jewel for the serious collector. Pearl white finish with gold accents, opening panoramic sunroof, and a lavishly detailed cabin.",
    features: [
      "1:18 scale",
      "Pearl white finish",
      "Opening sunroof",
      "Gold badge detail",
      "Plush interior replica",
      "Premium gift packaging",
    ],
    inStock: true,
    sku: "DXM-118-002",
  },
  {
    id: 7,
    slug: "lamborghini-urus-orange-118",
    name: "1:18 Lamborghini Urus – Gloss Orange",
    shortName: "Lamborghini Urus Orange",
    price: 2799,
    oldPrice: 3499,
    priceStr: "₹2,799",
    oldPriceStr: "₹3,499",
    scale: "1:18",
    category: "1:18",
    img: "/images/car-phantom.png",
    images: ["/images/car-phantom.png"],
    badge: null,
    description:
      "Gloss orange Lamborghini Urus in 1:18 scale. Aggressive styling, massive alloy wheels, and ultra-detailed aero body panels. This model demands attention wherever it's placed.",
    features: [
      "Gloss orange finish",
      "Oversized alloy wheel replicas",
      "Full Lamborghini badging",
      "Detailed exhaust",
      "Opening doors",
      "1:18 scale precision",
    ],
    inStock: true,
    sku: "DXM-118-003",
  },
  {
    id: 8,
    slug: "porsche-cayenne-grey-118",
    name: "1:18 Porsche Cayenne – Graphite Grey",
    shortName: "Porsche Cayenne Grey",
    price: 2599,
    oldPrice: 3299,
    priceStr: "₹2,599",
    oldPriceStr: "₹3,299",
    scale: "1:18",
    category: "1:18",
    img: "/images/car-vintage.png",
    images: ["/images/car-vintage.png"],
    badge: "New",
    description:
      "Sleek graphite grey Porsche Cayenne in 1:18 scale. Immaculate body lines, detailed Porsche badging, and sport alloy wheel replicas. A perfect addition to a premium display.",
    features: [
      "Graphite grey finish",
      "Porsche detailed badging",
      "Sport alloy replicas",
      "Detailed brake callipers",
      "Full interior",
      "Collector series packaging",
    ],
    inStock: true,
    sku: "DXM-118-004",
  },

  /* ── RC ──────────────────────────────────────────────────── */
  {
    id: 9,
    slug: "rc-racing-set-red-blue",
    name: "RC Racing Set – Red & Blue Combo",
    shortName: "RC Racing Set",
    price: 799,
    oldPrice: 1099,
    priceStr: "₹799",
    oldPriceStr: "₹1,099",
    scale: "RC",
    category: "RC",
    img: "/images/rc-car.png",
    images: ["/images/rc-car.png"],
    badge: "Popular",
    description:
      "Twin-pack RC racing set — red and blue cars with two controllers included. 2.4GHz frequency for zero interference. Speed up to 20 km/h on flat ground. Ideal gift for kids aged 5+.",
    features: [
      "Twin car pack (Red + Blue)",
      "2.4GHz no-interference",
      "Up to 20 km/h speed",
      "360° spin stunts",
      "Rechargeable via USB",
      "Age 5+",
    ],
    inStock: true,
    sku: "DXM-RC-001",
  },
  {
    id: 10,
    slug: "rc-suv-white",
    name: "RC Off-Road SUV Truck – White",
    shortName: "RC Off-Road SUV White",
    price: 1099,
    oldPrice: 1399,
    priceStr: "₹1,099",
    oldPriceStr: "₹1,399",
    scale: "RC",
    category: "RC",
    img: "/images/rc-car-white.png",
    images: ["/images/rc-car-white.png"],
    badge: null,
    description:
      "Large-scale RC off-road SUV truck in white. 4WD drive system, suspension for rough terrain, headlights and tail lights, and a 40m remote range. Built tough for outdoor play.",
    features: [
      "4WD all-terrain",
      "Working headlights",
      "40m remote range",
      "Independent suspension",
      "Rechargeable battery",
      "Age 6+",
    ],
    inStock: true,
    sku: "DXM-RC-002",
  },
  {
    id: 11,
    slug: "rc-drift-black",
    name: "RC Drift Car – Black Edition",
    shortName: "RC Drift Car Black",
    price: 699,
    oldPrice: 999,
    priceStr: "₹699",
    oldPriceStr: "₹999",
    scale: "RC",
    category: "RC",
    img: "/images/rc-car.png",
    images: ["/images/rc-car.png"],
    badge: "Sale",
    description:
      "Sleek black RC drift car with drift tyres for insane sideways action. Rear-wheel drive for realistic drifting, 2.4GHz control, and LED underglow lights.",
    features: [
      "Drift-spec tyres",
      "Rear-wheel drive",
      "LED underglow lights",
      "2.4GHz controller",
      "USB rechargeable",
      "Age 8+",
    ],
    inStock: true,
    sku: "DXM-RC-003",
  },
  {
    id: 12,
    slug: "rc-formula-racer",
    name: "RC Formula Racer – Championship Series",
    shortName: "RC Formula Racer",
    price: 1299,
    oldPrice: 1699,
    priceStr: "₹1,299",
    oldPriceStr: "₹1,699",
    scale: "RC",
    category: "RC",
    img: "/images/rc-car-formula.png",
    images: ["/images/rc-car-formula.png"],
    badge: "New",
    description:
      "Championship-spec RC formula one racer. Ultra-low profile body, slick race tyres, 2.4GHz 40km/h top speed, and LED cockpit detail. The fastest car in the DaxoMart lineup.",
    features: [
      "Formula 1 body design",
      "Slick race tyres",
      "Top speed 40 km/h",
      "LED cockpit detail",
      "2.4GHz precise steering",
      "Age 10+",
    ],
    inStock: true,
    sku: "DXM-RC-004",
  },

  /* ── 3D Frames ───────────────────────────────────────────── */
  {
    id: 13,
    slug: "3d-frame-orange-edition",
    name: "3D Car Display Frame – Orange Edition",
    shortName: "3D Frame Orange",
    price: 1999,
    oldPrice: 2499,
    priceStr: "₹1,999",
    oldPriceStr: "₹2,499",
    scale: "Frame",
    category: "Frame",
    img: "/images/display-frame.png",
    images: ["/images/display-frame.png"],
    badge: "Best Seller",
    description:
      "Wall-mounted 3D diorama display frame in a dramatic orange-black colour scheme. Includes a 1:24 scale die-cast sports car pre-installed. LED strip lighting illuminates the entire display.",
    features: [
      "Includes 1:24 car",
      "LED strip lighting",
      "Wall-mount ready",
      "Orange-black theme",
      "Acrylic display cover",
      "Gift packaged",
    ],
    inStock: true,
    sku: "DXM-FRM-001",
  },
  {
    id: 14,
    slug: "3d-frame-blue-edition",
    name: "3D Car Display Frame – Blue Edition",
    shortName: "3D Frame Blue",
    price: 2199,
    oldPrice: 2799,
    priceStr: "₹2,199",
    oldPriceStr: "₹2,799",
    scale: "Frame",
    category: "Frame",
    img: "/images/display-frame-blue.png",
    images: ["/images/display-frame-blue.png"],
    badge: "New",
    description:
      "Premium 3D wall display frame in electric blue and white. Includes 1:18 scale supercar pre-installed with track-detail base, LED lighting, and acrylic protective cover.",
    features: [
      "Includes 1:18 car",
      "Blue-white theme",
      "Track detail base",
      "LED lighting",
      "Acrylic cover",
      "Premium packaging",
    ],
    inStock: true,
    sku: "DXM-FRM-002",
  },
  {
    id: 15,
    slug: "3d-frame-dark-edition",
    name: "3D Car Display Frame – Dark Edition",
    shortName: "3D Frame Dark",
    price: 1799,
    oldPrice: 2299,
    priceStr: "₹1,799",
    oldPriceStr: "₹2,299",
    scale: "Frame",
    category: "Frame",
    img: "/images/display-frame-dark.png",
    images: ["/images/display-frame-dark.png"],
    badge: null,
    description:
      "Understated dark edition 3D display frame for the minimalist collector. Deep charcoal and matte black finish with subtle LED accent lighting. A gallery-quality display piece.",
    features: [
      "Charcoal-black theme",
      "Subtle LED accent",
      "Minimalist design",
      "Wall-mount ready",
      "Acrylic cover",
      "Collector certificate",
    ],
    inStock: true,
    sku: "DXM-FRM-003",
  },
];

export default PRODUCTS;

export function getProduct(id: number) {
  return PRODUCTS.find((p) => p.id === id) ?? null;
}

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug) ?? null;
}

export function getProductsByCategory(cat: Product["category"]) {
  return PRODUCTS.filter((p) => p.category === cat);
}
